# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.1.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Feature Scaling

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [18]:
print(X)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


### Splitting the dataset into the Training set and Test set

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [20]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [21]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [22]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [23]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [24]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [25]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 75us/sample - loss: 0.5348 - accuracy: 0.7845
Epoch 2/100
8000/8000 [==============================] - 0s 53us/sample - loss: 0.4581 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 45us/sample - loss: 0.4395 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 0s 52us/sample - loss: 0.4317 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 63us/sample - loss: 0.4277 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 0s 51us/sample - loss: 0.4251 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 0s 61us/sample - loss: 0.4226 - accuracy: 0.8095
Epoch 8/100
8000/8000 [==============================] - 0s 47us/sample - loss: 0.4206 - accuracy: 0.8191
Epoch 9/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.4183 - accuracy: 0.8210
Epoch 10/100
8000/8000 [

8000/8000 [==============================] - 0s 49us/sample - loss: 0.3368 - accuracy: 0.8615
Epoch 78/100
8000/8000 [==============================] - 0s 50us/sample - loss: 0.3373 - accuracy: 0.8621
Epoch 79/100
8000/8000 [==============================] - 0s 61us/sample - loss: 0.3367 - accuracy: 0.8618
Epoch 80/100
8000/8000 [==============================] - 0s 42us/sample - loss: 0.3366 - accuracy: 0.8608
Epoch 81/100
8000/8000 [==============================] - 0s 44us/sample - loss: 0.3364 - accuracy: 0.8629
Epoch 82/100
8000/8000 [==============================] - 0s 47us/sample - loss: 0.3366 - accuracy: 0.8629
Epoch 83/100
8000/8000 [==============================] - 0s 57us/sample - loss: 0.3362 - accuracy: 0.8619
Epoch 84/100
8000/8000 [==============================] - 0s 62us/sample - loss: 0.3358 - accuracy: 0.8620
Epoch 85/100
8000/8000 [==============================] - 0s 61us/sample - loss: 0.3358 - accuracy: 0.8605
Epoch 86/100
8000/8000 [==========================

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [26]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [27]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1525   70]
 [ 201  204]]
